### ISSUE TITLE
Content Types Fields Not Showing in Export

### ISSUE THREAD

**Issue by natloh** [parallelus/Content-Types-for-Runway#13]
Hi, I'll just start by saying this is a great platform and it has helped me build several wordpress themes.

However, I have created a custom type using the extension, but the field that goes along with them are not showing up when I export as a standalone theme.

**Comment by parallelus** [comment]
Thanks for the feedback, and letting us know about the error.

Have you tested the 'develop' branch? Sometimes we will have fixes on there not yet pushed to the master release. You can download it here: https://github.com/parallelus/Content-Types-for-Runway/archive/develop.zip

If you have the same problem with the development version, let me know and I'll make sure we dig into the code and find out why this isn't working. 

Thanks!

**Comment by natloh** [comment]
I tried the development version, and it still didn't work. Where does the
extension store its data?

**Comment by parallelus** [comment]
Data is stored in `{your child theme}/data` folder with a descriptive name like, `XXXXX_content_types.json`

We will take a look at this for you and see what's happening.

**Comment by natloh** [comment]
And where is the file that pulls the data for the development site to work?

**Comment by parallelus** [comment]
It's the same file for both.

**Comment by natloh** [comment]
Ok I'll look around and see if I can find the problem. Thanks.
